### ISSUE TITLE
Use type Individual versus Patient

### ISSUE THREAD

**Issue by bwalsh** [ohsu-computational-biology/ccc_client#10]
https://github.com/ga4gh/schemas/blob/biosample/src/main/resources/avro/biometadata.avdl#L16-L70

**Comment by buchanae** [comment]
That link is a 404 now. Could you clarify, or let me know that we can close this issue?

**Comment by bwalsh** [comment]
https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/bio_metadata.proto#L12

**Comment by buchanae** [comment]
Ok, thank, still not sure what needs to be done here though. I don't see any use of protobufs in this repo.

**Comment by bwalsh** [comment]
The properties used in https://github.com/ohsu-computational-biology/ccc_client/blob/master/ccc_client/resources/domains.json#L2  should align with the schemas' properties.

**Comment by mayfielg** [comment]
Brian, Alex, I'm working on some edits to the domains.json file that do just that for compatibility with the dms protobuf schemas were working on in the gdc_experimental repo. I've put them on a branch called dms_load that I have not yet pushed up.

**Comment by mayfielg** [comment]
Domains file currently follows GDC schema, as it is used with the CCC_DMS, which also follows GDC schema internally, and also duplicates select fields so it is additionally in line with GA4GH for querying capabilities.
